variable "metro" {}
variable "vrf_desc" {}
variable "vrf_desc_sec" {}
variable "vrf_name" {}
variable "vrf_name_sec" {}
variable "vrf_asn" {}
variable "vrf_ranges" {}
variable "vrf_ranges_sec" {}
variable "project_id" {}
variable "vlan_desc" {}
variable "vlan_desc_sec" {}
variable "range_desc_pri" {}
variable "range_desc_sec" {}
variable "cidr" {}
variable "network_range_pri" {}
variable "network_range_sec" {}