variable "metro" {}
variable "vrf_desc" {}
variable "vrf_name" {}
variable "vrf_asn" {}
variable "vrf_ranges" {}
variable "project_id" {}
variable "vlan_desc" {}
variable "range_desc" {}
variable "cidr" {}
variable "network_range" {}